export const CATEGORIES_CHANGE = 'CATEGORIES_CHANGE';
export const EXPENSES_CHANGE = 'EXPENSES_CHANGE';
export const INVALID_CATEGORY_ID = 'INVALID_CATEGORY_ID';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
